src/Entity/Booking.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BookingRepository")
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Customer", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $customer;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Cleaner", inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $cleaner;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $duration;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quality_score;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): self
    {
        $this->customer = $customer;

        return $this;
    }

    public function getCleaner(): ?Cleaner
    {
        return $this->cleaner;
    }

    public function setCleaner(?Cleaner $cleaner): self
    {
        $this->cleaner = $cleaner;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration($duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getQualityScore(): ?int
    {
        return $this->quality_score;
    }

    public function setQualityScore(?int $quality_score): self
    {
        $this->quality_score = $quality_score;

        return $this;
    }
}

src/Entity/Cleaner.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CleanerRepository")
 */
class Cleaner
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank()
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank()
     */
    private $last_name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quality_score;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City", inversedBy="cleaners")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Booking", mappedBy="cleaner")
     */
    private $bookings;

    public function __construct()
    {
        $this->bookings = new ArrayCollection();
    }

    //==========================

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getQualityScore(): ?int
    {
        return $this->quality_score;
    }

    public function setQualityScore(?int $quality_score): self
    {
        $this->quality_score = $quality_score;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setCleaner($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getCleaner() === $this) {
                $booking->setCleaner(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\City;
use App\Entity\Cleaner;
use App\Entity\Customer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;


/**
 * Class BookingController
 * @package App\Controller
 */
class BookingController extends AbstractController
{
    /**
     * @Route("/booking/create/select_params", methods={"GET","POST"}, name="select_params")
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function selectParams(Request $request)
    {
        if($request->isMethod('POST'))
        {
            $params = $request->request;

            // validation (not blank)
            $errors = [];
            foreach($params as $key => $value)
            {
                if(empty($value))
                    $errors[] = strtoupper($key) .  " => This value should not be blank";
            }
            if(count($errors) > 0)
                return $this->render('validation.html.twig', [
                    'errors' => $errors,
                    'back' => '/booking/create/select_params'
                ]);

            $session = $this->get('session');

            $session->set('date', $params->get('date'));
            $session->set('city_id', $params->get('city'));
            $session->set('duration', $params->get('duration'));


            return $this->redirectToRoute('select_cleaner');
        }

        $cities = $this->getDoctrine()->getRepository(City::class)
            ->findBy(['is_active' => '1']);

        return $this->render('booking/selectParams.html.twig', ['cities' => $cities]);
    }

    /**
     * @Route("/booking/create/select_cleaner", methods={"GET","POST"}, name="select_cleaner")
     *
     * @return Response
     * @throws \Exception
     */
    public function selectCleaner()
    {
        $session = $this->get('session');

        $bookings = $this->getDoctrine()->getRepository(Booking::class)->getPossibleBookings();

        $strBegin = str_replace('T', ' ', $session->get('date'));
        $begin = \DateTime::createFromFormat('Y-m-d H:i', $strBegin);
        $end = clone $begin;
        $end->add(new \DateInterval('PT' . $session->get('duration') . 'H'));

        $city = $this->getDoctrine()->getRepository(City::class)->find($session->get('city_id'));
        $freeCleaners = $this->getDoctrine()->getRepository(Cleaner::class)
            ->findBy(['city' => $city]);

        foreach($bookings as $b)
        {
            $bookBegin = $b->getDate();
            $bookEnd = clone $bookBegin;
            $bookEnd->add(new \DateInterval('PT' . $b->getDuration() . 'H'));


            if( ($end >= $bookBegin && $end <= $bookEnd) || ($begin >= $bookBegin && $begin <= $bookEnd) ||
                ($bookEnd >= $begin && $bookEnd <= $end) || ($bookBegin >= $begin && $bookBegin <= $end))
            {
                $cleaner = $b->getCleaner();

                if(in_array($cleaner, $freeCleaners))
                {
                    unset($freeCleaners[array_search($cleaner, $freeCleaners)]);
                }
            }
        }

        if(count($freeCleaners) > 0)
        {
            return $this->render('booking/selectCleaner.html.twig',[
                'city' => $this->getDoctrine()->getRepository(City::class)->find($session->get('city_id')),
                'date' => $session->get('date'),
                'duration' => $session->get('duration'),
                'cleaners' => $freeCleaners
            ]);
        }
        else
        {
            return $this->render('booking/noFreeCleaners.html.twig');
        }
    }

    /**
     * @Route("/booking/create/finish", methods={"GET", "POST"}, name="create_booking")
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function create(Request $request)
    {
        $session = $this->get('session');

        if($request->isMethod('post'))
        {
            $doctrine = $this->getDoctrine();

            $cleaner_id = $request->request->get('cleaner');
            $strDate = str_replace('T', ' ', $session->get('date'));

            $date = \DateTime::createFromFormat('Y-m-d H:i', $strDate);
            $cleaner = $doctrine->getRepository(Cleaner::class)->find($cleaner_id);
            $customer = $doctrine->getRepository(Customer::class)->find($session->get('customer_id'));

            $booking = new Booking();
            $booking->setDate($date);
            $booking->setDuration($session->get('duration'));
            $booking->setCleaner($cleaner);
            $booking->setCustomer($customer);

            $entityManager = $doctrine->getManager();
            $entityManager->persist($booking);
            $entityManager->flush();

            $session->clear();

            return $this->render('booking/createSuccessfully.html.twig', [
                'booking' => $booking
            ]);
        }
        return $this->redirectToRoute('select_cleaner');
    }


//======= admin/ ========//

    /**
     * @Route("/admin/booking/index", name="admin_booking_index")
     *
     * @return Response
     */
    public function index()
    {
        $doctrine = $this->getDoctrine();

        $bookings = $doctrine->getRepository(Booking::class)->findAllSorted();

        return $this->render('booking/index.html.twig', [
            'bookings' => $bookings,
            'tableName' => 'All bookings'
        ]);
    }

    /**
     * @Route("/admin/booking/index/actual", name="admin_booking_index_actual")
     *
     * @return Response
     */
    public function indexActual()
    {
        $doctrine = $this->getDoctrine();

        $bookings = $doctrine->getRepository(Booking::class)->getPossibleBookings();

        return $this->render('booking/index.html.twig', [
            'bookings' => $bookings,
            'tableName' => 'Actual bookings'
        ]);
    }

    /**
     * @Route("/admin/booking/delete/{id}", methods={"DELETE"}, name="admin_booking_delete")
     *
     * @param Request $request
     * @param $id
     */
    public function delete(Request $request, $id)
    {
        $booking = $this->getDoctrine()->getRepository(Booking::class)
            ->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($booking);
        $entityManager->flush();

        $response = new Response();
        $response->send();
    }

    /**
     * @Route("/admin/booking/edit/{id}", methods={"GET", "POST"}, name="admin_booking_edit")
     *
     * @param Request $request
     * @param ValidatorInterface $validator
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     */
    public function edit(Request $request, ValidatorInterface $validator, $id)
    {
        if($request->isMethod('POST'))
        {
            $entityManager = $this->getDoctrine()->getManager();
            $booking = $entityManager->getRepository(Booking::class)->find($id);

            $booking->setCleaner(
                $this->getDoctrine()->getRepository(Cleaner::class)->find($request->request->get('cleaner'))
            );

            $strDate = $request->request->get('date');
            $strDate = str_replace('T', ' ', $strDate);
            $date = \DateTime::createFromFormat('Y-m-d H:i', $strDate);

            if($date){
                $booking->setDate($date);
            }

            $booking->setDuration($request->request->get('duration'));

            $arr_errors = $validator->validate($booking);

            if (count($arr_errors) > 0)
            {
                return $this->showDanger($arr_errors, '/admin/booking/edit/' . $id);
            }
            else
            {
                $entityManager->flush();
                return $this->redirectToRoute('admin_booking_index');
            }
        }

        $booking = $this->getDoctrine()->getRepository(Booking::class)->find($id);

        $date = $booking->getDate()->format('Y-m-d H:i:s');
        $date = str_replace(' ', 'T', $date);

        $cleaners = $this->getDoctrine()->getRepository(Cleaner::class)
            ->findBy([
                'city' => $booking->getCleaner()->getCity()
            ]);

        return $this->render('booking/edit.html.twig', [
            'booking'   => $booking,
            'date'      => $date,
            'cleaners'  => $cleaners
        ]);
    }

    /**
     * Redirect to page with errors
     *
     * @param array $arr_errors
     * @param string $back
     * @return Response
     */
    private function showDanger($arr_errors, string $back)
    {
        $errors = [];

        foreach($arr_errors as $error)
        {
            $errors[] = strtoupper($error->getPropertyPath()) . ' => ' . $error->getMessage();
        }
        return $this->render('validation.html.twig', [
            'errors' => $errors,
            'back' => $back
        ]);
    }
}

templates/booking/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create booking{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-4 offset-4">

            <form action="/booking/create/select_params" class="form-horizontal" method="POST">
                <h2>Create new booking</h2>

                <div class="form-group">
                    <label for="date" class="col-form-label">Date and time</label>
                    <input type="datetime-local" class="form-control" name="date">
                </div>

                <div class="form-group">
                    <label for="city" class="col-form-label">City</label>
                    <select class="custom-select" name="city">
                        {% for city in cities %}
                            <option value = "{{ city.id }}">{{ city.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="duration" class="col-form-label">Duration (hours)</label>
                    <input type="number" class="form-control" name="duration">
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Find cleaners</button>
                </div>

            </form>

        </div>
    </div>

{% endblock %}

templates/booking/createSuccessfully.html.twig
{% extends 'base.html.twig' %}

{% block title %}Created successfully{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-4 offset-4">

            <div class="card border-success mb-3" >
                <div class="card-header">Booking for {{ booking.customer.firstName }} {{ booking.customer.lastName }}</div>
                <div class="card-body">
                    <b><h5 class="card-title">City</h5></b>
                    <p class="card-text">{{ booking.cleaner.city.name }}</p>
                    <h5 class="card-title">Date and time</h5>
                    <p class="card-text">{{ booking.date|date('Y-m-d H-i') }}</p>
                    <h5 class="card-title">Duration</h5>
                    <p class="card-text">{{ booking.duration }} hours</p>
                    <h5 class="card-title">Cleaner</h5>
                    <p class="card-text">{{ booking.cleaner.firstName }} {{ booking.cleaner.lastName }}</p>
                </div>
            </div>

            <a href="/" class="btn btn-primary btn-block">Home</a>

        </div>
    </div>

{% endblock %}

templates/booking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}

    <div class="row">

        {{ include('inc/admin_sidebar.html.twig') }}

        <div class=" col-md-4 offset-2">

            <form action="/admin/booking/edit/{{ booking.id }}" method="POST" class="form-horizontal">
                <div class="card border-primary">
                    <div class="card-header">
                        <p>Booking of {{ booking.customer.firstName }} {{ booking.customer.lastName }}</p>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            City: {{ booking.cleaner.city.name }}
                        </h5>
                        <div class="form-group">
                            <label for="date" class="col-form-label">Date</label>
                            <input type="datetime-local" class="form-control" name="date" value="{{ date }}">
                        </div>

                        <div class="form-group">
                            <label for="duration" class="col-form-group">Duration</label>
                            <input type="number" class="form-control" name="duration" value="{{ booking.duration }}">
                        </div>

                        <div class="form-group">
                            <label for="cleaner" class="col-form-label">Cleaner</label>
                            <select class="custom-select" name="cleaner">
                                {% for cleaner in cleaners %}
                                    <option value = "{{ cleaner.id }}">{{ cleaner.firstName }} {{ cleaner.lastName }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                </div>
            </form>
        </div>

    </div>


{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}

    <div class="row">

        {{ include('inc/admin_sidebar.html.twig') }}

        <div class=" col-md-8">

            <h4>{{ tableName }}</h4>

            {#----------- TABLE -----------#}
            <table id="bookings" class="table table-hover table-sm">
                <thead>
                <tr>
                    <th scope="col">Booking id</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Cleaner</th>
                    <th scope="col">Date</th>
                    <th scope="col">Duration</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>

                {% for b in bookings %}
                    <tr>
                        <th scope="row">{{ b.id }}</th>
                        <td>{{ b.customer.firstName}} {{ b.customer.lastName }}</td>
                        <td>{{ b.cleaner.firstName }} {{ b.cleaner.lastName }}</td>
                        <td>{{ b.date|date('Y.m.d - H:i') }}</td>
                        <td>{{ b.duration }}</td>
                        <td>
                            <a href="/admin/booking/edit/{{ b.id }}" class="btn btn-outline-info btn-sm">Edit</a>
                            <a href="#" class="btn btn-outline-danger btn-sm" data-id="{{ b.id }}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>


        </div>

    </div>


{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}

templates/booking/noFreeCleaners.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create booking{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-4 offset-4">

            <div class="card text-white bg-warning mb-3">
                <div class="card-header">Warning!</div>
                <div class="card-body">
                    <h4 class="card-title">No appropriate cleaners</h4>
                    <p class="card-text">All cleaners are busy. Please, go back and choose other parameters...</p>
                    <a href="/booking/create/select_params"></a>
                </div>
            </div>

        </div>
    </div>

{% endblock %}

templates/booking/selectCleaner.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create booking{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-4 offset-4">

            <div class="card border-success mb-3" >
                <div class="card-header">Booking parameters</div>
                <div class="card-body">
                    <b><h5 class="card-title">City</h5></b>
                    <p class="card-text">{{ city.name }}</p>
                    <h5 class="card-title">Date and time</h5>
                    <p class="card-text">{{ date }}</p>
                    <h5 class="card-title">Duration</h5>
                    <p class="card-text">{{ duration }} hours</p>
                </div>
            </div>

            <form action="/booking/create/finish" class="form-horizontal" method="POST">

                <div class="form-group">
                    <label for="cleaner" class="col-form-label">Cleaner</label>
                    <select class="custom-select" name="cleaner">
                        {% for cleaner in cleaners %}
                            <option value = "{{ cleaner.id }}">{{ cleaner.firstName }} {{ cleaner.lastName }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Save booking</button>
                </div>

            </form>

        </div>
    </div>

{% endblock %}

templates/booking/selectParams.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create booking{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-4 offset-4">

            <form action="/booking/create/select_params" class="form-horizontal" method="POST">
                <h2>Create new booking</h2>

                <div class="form-group">
                    <label for="date" class="col-form-label">Date and time</label>
                    <input type="datetime-local" class="form-control" name="date">
                </div>

                <div class="form-group">
                    <label for="city" class="col-form-label">City</label>
                    <select class="custom-select" name="city">
                        {% for city in cities %}
                            <option value = "{{ city.id }}">{{ city.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="duration" class="col-form-label">Duration (hours)</label>
                    <input type="number" class="form-control" name="duration">
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Next (find cleaners)</button>
                </div>

            </form>

        </div>
    </div>

{% endblock %}