src/Entity/City.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CityRepository")
 */
class City
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Cleaner", mappedBy="city")
     */
    private $cleaners;

    //===========================

    public function __construct()
    {
        $this->cleaners = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    /**
     * @return Collection|Cleaner[]
     */
    public function getCleaners(): Collection
    {
        return $this->cleaners;
    }

    public function addCleaner(Cleaner $cleaner): self
    {
        if (!$this->cleaners->contains($cleaner)) {
            $this->cleaners[] = $cleaner;
            $cleaner->setCity($this);
        }

        return $this;
    }

    public function removeCleaner(Cleaner $cleaner): self
    {
        if ($this->cleaners->contains($cleaner)) {
            $this->cleaners->removeElement($cleaner);
            // set the owning side to null (unless already changed)
            if ($cleaner->getCity() === $this) {
                $cleaner->setCity(null);
            }
        }

        return $this;
    }

}

src/Controller/CityController.php
<?php

namespace App\Controller;

use App\Entity\City;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class CityController extends AbstractController
{
    /**
     * @Route("/admin/city/index", methods={"GET", "POST"}, name="admin_cities_index")
     */
    public function index(Request $request)
    {
        if($request->isMethod('POST'))
        {
            $arr = $request->request->all();

            $manager = $this->getDoctrine()->getManager();
            $manager->getRepository(City::class)->resetActivity();

            $cities = $manager->getRepository(City::class)->findAll();

            foreach ($cities as $city)
            {
                dump($city->getId());
                dump($arr);
                if(key_exists($city->getId(), $arr))
                    $city->setIsActive(1);
            }

            $manager->flush();

            return $this->redirectToRoute('admin_booking_index');
        }

        $cities = $this->getDoctrine()->getRepository(City::class)->findAll();

        return $this->render('city/index.html.twig', [
            'cities' => $cities
        ]);
    }

    /**
     * @Route("/admin/city/delete/{id}", methods={"DELETE"}, name="admin_cities_delete")
     */
    public function delete(Request $request, $id)
    {
        $city = $this->getDoctrine()->getRepository(City::class)
            ->find($id);

        $manager = $this->getDoctrine()->getManager();
        $manager->remove($city);
        $manager->flush();

        $res = new Response();
        $res->send();
    }

    /**
     * @Route("/admin/city/create", methods={"GET", "POST"}, name="admin_cities_create")
     */
    public function add(Request $request, ValidatorInterface $validator)
    {
        if($request->isMethod('POST'))
        {
            $cityName = $request->request->get('city');

            $city = new City();
            $city->setName($cityName);
            $city->setIsActive(0);

            $arr_errors = $validator->validate($city);
            if (count($arr_errors) > 0)
            {
                return $this->showDanger($arr_errors);
            }
            else
            {
                $manager = $this->getDoctrine()->getManager();
                $manager->persist($city);
                $manager->flush();

                return $this->redirectToRoute('admin_cities_index');
            }
        }

        return $this->render('city/create.html.twig');
    }

    /**
     * @param array of errors
     *
     * @return Response
     */
    private function showDanger($arr_errors)
    {
        $errors = [];

        foreach($arr_errors as $error)
        {
            $errors[] = strtoupper($error->getPropertyPath()) . ' => ' . $error->getMessage();
        }
        return $this->render('validation.html.twig', [
            'errors' => $errors,
            'back' => '/admin/city/create'
        ]);
    }
}

templates/city/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}

    <div class="row">
        <div class="col-md-4 offset-4">

            <form action="/admin/city/create" class="form-horizontal" method="POST">
                <h2>Create new City</h2>

                <div class="form-group">
                    <label for="city" class="col-form-label">City</label>
                    <input type="text" class="form-control" name="city">
                </div>


                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                </div>

            </form>

        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}

templates/city/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dashboard{% endblock %}

{% block body %}

    <div class="row">

        {{ include('inc/admin_sidebar.html.twig') }}

        <div class=" col-md-8">
            <div class="row my-sm-3">
                <h5>Cities</h5>
                <a href="/admin/city/create" class="btn btn-outline-primary btn-sm ml-auto">Add city</a>
            </div>

            <form action="/admin/city/index" method="POST" class="form-horizontal">
                <table id="cities" class="table table-hover table-sm">
                    <thead>
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">Name</th>
                        <th scope="col">is active</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for c in cities %}
                        <tr>
                            <th scope="row">{{ c.id }}</th>
                            <td>{{ c.name }}</td>
                            <td>
                                <div class="form-group">
                                    <input type="checkbox" name="{{ c.id }}" value="{{ c.isActive }}"
                                            {% if c.isActive %}
                                                checked
                                            {% endif %}
                                    >
                                </div>
                            </td>
                            <td>
                                <a href="#" class="btn btn-outline-danger btn-sm" data-id="{{ c.id }}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

                <div class="row">
                    <div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-outline-primary btn-sm offset-2">Save changes</button>
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>


{% endblock %}

{% block javascripts %}
    <script src="/js/main.js"></script>
{% endblock %}